<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('active_websocket_connections', function (Blueprint $table) {
            $table->id();

            // Unique ID generated by the Java WebSocket server
            $table->string('connection_id')->unique();

            // Laravel user ID
            $table->foreignId('user_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            // lecturer / student
            $table->string('role', 30);

            // UUID of the classroom on the Java server
            $table->string('classroom_id')->index();

            // IP address of the WebSocket client
            $table->ipAddress('ip_address')->nullable();

            // When Java accepted the WebSocket connection
            $table->timestamp('connected_at');

            $table->timestamps();

            // Useful for admin queries
            $table->index(['role', 'connected_at']);
            $table->index(['classroom_id', 'connected_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('active_websocket_connections');
    }
};